version: 2

updates:
  - package-ecosystem: "npm"
    directory: "./"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    open-pull-requests-limit: 15
    target-branch: "main"
    commit-message:
      prefix: "Node Package Update: "

  # - package-ecosystem: "docker"
  #   directory: "./"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 3
  #   target-branch: "main"
  #   commit-message:
  #     prefix: "Docker Image Update: "